### ISSUE TITLE
Spotify doesn't return all song data

### ISSUE THREAD

**Issue by aCluelessDanny** [aCluelessDanny/UeberPlayer#1]
So I never knew about this because I didn't update Spotify until now, but apparently, [Spotify broke its Applescript implementation a bit](https://community.spotify.com/t5/Desktop-Mac/Applescript-no-longer-reports-Spotify-Connect-song-playing/m-p/4925257) about a month ago.

The details are that the song name and the artist name are returned as empty strings when a user interacts with the currently playing track (playing, pausing, skipping, etc.). When the track changes naturally on its own, it _does_ work normally.

Unfortunately this is something out of my hands. I could switch to using Spotify's Web API, but I'm gonna wait to see if this gets fixed soon. For now, if you want to use this widget without this bug, revert Spotify back to _1.1.30.658_.

This issue will be closed when it's patched up or I go the Web API route.

**Comment by syto203** [comment]
im on spotify 1.1.31 and track retrieval is working fine even when manually changing the playing track and its status.

**Comment by aCluelessDanny** [comment]
It wasn't working on that version for me at the time (and I couldn't really check that well because of college taking up my time), buuut
I can confirm that 1.1.34.694 has fixed the issue on my end and in the discussion board, so this can be closed now~
