### ISSUE TITLE
Possible to turn off 'auto hide'?

### ISSUE THREAD

**Issue by PeteSSMMSS** [aCluelessDanny/UeberPlayer#11]
Thanks for the lovely widget! I´m using this on a second screen, and want to have it displayed, even if Spotify is paused or not running... is this possible?

**Comment by aCluelessDanny** [comment]
It should be possible, yeah! Just need to add an extra check in a couple of places, but that sounds like a nice addition. I'll get right on that~

**Comment by aCluelessDanny** [comment]
A new release is up with some visibility options for this now~
Should be good for your use case and you can read about it [here](https://github.com/aCluelessDanny/UeberPlayer#visibility).
Do tell if it works out alright for ya
