### ISSUE TITLE
An update possible

### ISSUE THREAD

**Issue by GrimlocK38** [aCluelessDanny/UeberPlayer#4]
Hi,

`Which job. just fantastic.`

Can it be adapted for the Music application ?

Thanks

**Comment by Silentbob101** [comment]
bump :)

**Comment by GrimlocK38** [comment]
Oh yess :)

**Comment by aCluelessDanny** [comment]
I'm not sure what you mean by the question, ahah.
If you meant you'd like support for Apple's native Music app, it's already had support for it, so there's no problem there

**Comment by GrimlocK38** [comment]
Hi,

it works with the native music with the system catalina ?

Thanks

**Comment by aCluelessDanny** [comment]
Yup! It should work perfectly fine with the native Music app

**Comment by GrimlocK38** [comment]
Hi,

in your description you do not indicate it. I will test :)

**Comment by GrimlocK38** [comment]
> Yup! It should work perfectly fine with the native Music app

I just tested and the player does not appear. 

MacOS: 10.15.5

i want this player 🤪

Thanks

**Comment by aCluelessDanny** [comment]
Oh? I use MacOS 10.15.5 too, and it works perfectly fine for me.
Does the console log say anything by any chance?

**Comment by GrimlocK38** [comment]
Hi,

Here is
<img width="1068" alt="ITRecords 1" src="https://user-images.githubusercontent.com/19632490/85941017-6d2d5180-b920-11ea-83e2-e465c834d7ce.png">
<img width="1068" alt="ITRecords 2" src="https://user-images.githubusercontent.com/19632490/85941020-71596f00-b920-11ea-9241-3efd215599bc.png">

**Comment by aCluelessDanny** [comment]
It's a bit hard to say with this, but I just put out a release that fixes a pretty bad error for people who don't have Spotify installed, so maybe this also applies here? Give it a try if you can

**Comment by nhlondon** [comment]
I was getting the same error. For me it appears to have come from the .widget being removed from directory when extracting the zip file making all of the file paths in the index.jsx file wrong. Changing the directory name include the .widget fixed the issue (at least with the newest release)
