### ISSUE TITLE
Widget fails to run if Spotify isn't installed

### ISSUE THREAD

**Issue by puzzledsam** [aCluelessDanny/UeberPlayer#5]
I've been wanting to use this widget but every time I play something on Apple Music, nothing happens. Looking at the console, it seems that it's looking for a Spotify install. Since I don't have it installed on my Mac, the widget crashes and never pops up.

**Comment by aachh** [comment]
What error are you getting in the debug console?

**Comment by puzzledsam** [comment]
I see the following error message being repeated over and over:

> [Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (run, line 0)
[Log] Something happened!? Error: UeberPlayer.widget/getTrack.scpt:803:808: script error: Expected “then”, etc. but found identifier. (-2741) (UeberPlayer-widget-index-jsx, line 655)

By installing Spotify the error went away, and then once I uninstalled it, the error reappeared. The AppleScript which gets the currently playing information works fine on it's own according to the Script Editor's output, but fails to work properly in the widget.

**Comment by aCluelessDanny** [comment]
I think I managed to fix this problem. I completely forgot about people who don't have Spotify installed, and Applescript's _very_ finicky sometimes, haha. Try downloading the zip again and see if it works!

**Comment by puzzledsam** [comment]
With the new version I still get a similar error:
`[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (run, line 0)
[Log] Something happened!? Error: UeberPlayer.widget/getTrack.scpt:1290:1295: script error: Expected end of line but found identifier. (-2741) (UeberPlayer-widget-index-jsx, line 655)
`

**Comment by aCluelessDanny** [comment]
Gonna close this for now because I believe the update I made a bit ago should work fine without Spotify installed now, but feel free to reopen if the problem still persists
